### ISSUE TITLE
Commit panel doesn't open

### ISSUE THREAD

**Issue by RangerMauve** [akonwi/git-plus#310]
Hey, I just installed the latest version, 5.5.0, and it seems that the commit panel doesn't want to open up anymore. The little notification for "blah will be replaced by LF".

I'm on Windows 10 with Atom 1.1.0

**Comment by akonwi** [comment]
It doesn't open up at all? Are there any errors in the dev console?

**Comment by atom-project** [comment]
:+1:  same here

**Comment by RangerMauve** [comment]
All I have is this:

```
Uncaught (in promise) warning: LF will be replaced by CRLF in somefile.html.
The file will have its original line endings in your working directory.
```

which I think I've been getting for a while

**Comment by RangerMauve** [comment]
When I open in developer mode, the problem doesn't happen. Tried closing tabs, didn't have an effect.

**Comment by akonwi** [comment]
This might be sort of related to #302. Your git configurations for line endings are in play I think. You can turn this warning off with 'git config core.autocrlf true`. I'll try to push a possible fix in the next patch relase

**Comment by RangerMauve** [comment]
Well, the warning has been around for me for a while. I don't think it's causing the panel to not show up. The panel issue only started happening after I updated to 5.5.0.

**Comment by akonwi** [comment]
It's a problem now because it's an error within the promise to open the commit pane. Before the update, it was just ignored but it now breaks the promise chain because it isn't caught. I think I know where to catch it though.

**Comment by RangerMauve** [comment]
Makes sense! Changing that git config didn't seem to fix it. The warning thingie on the side didn't pop up, but the panel is still not opening.

**Comment by akonwi** [comment]
Dangit. This will be tough since I can't recreate it for myself. I'll try to create a special 'debug' branch that you can clone and replace your installation of the package with so we can get some more feedback.

**Comment by RangerMauve** [comment]
Sounds good! Would you like a list of the plugins I have in case they might look suspicious?

**Comment by akonwi** [comment]
This should be independent of those but it might be helpful to see a list of your plugins. 

I've pushed a new branch named `310`. Clone that and check the dev console when the error occurs. There should be some more informative output for me to determine the source of this.

**Comment by RangerMauve** [comment]
Still at work so can't be cloning and stuff yet, but I'll get to it in a couple of hours. :D

Here's a list of plugins in the meantime

```
├── atom-beautify@0.28.16
├── autoclose-html@0.19.0
├── black-and-white-ui@0.1.15
├── docblockr@0.7.3
├── file-icons@1.6.11
├── git-plus@5.5.0
├── language-cypher@0.3.0
├── language-dot@1.6.0
├── language-jsx@0.1.1
├── line-count@0.3.5
├── linter@1.10.0
├── linter-alex@1.5.0
├── linter-jshint@1.2.1
├── linter-jsonlint@1.0.1
├── open-terminal-here@2.1.0
├── project-switcher2@1.1.3
```

**Comment by RangerMauve** [comment]
The panel is opening properly now.

The console is printing `Error during "init"` on [this line](https://github.com/akonwi/git-plus/blob/310/lib/models/git-commit.coffee#L92)

**Comment by RangerMauve** [comment]
Seems that opening a second editor window for a different project made the panel not open again.

**Comment by akonwi** [comment]
I just pushed a new commit. Let me know how that works

**Comment by RangerMauve** [comment]
Seems to still be a little buggy. It's like I have to do the command twice for it to work. Twice to open the pane when I `add all and commit` and twice to trigger the commit after saving in the pane with `ctrl+s`. But it sort of works now which is good. :D

**Comment by RangerMauve** [comment]
In the console I'm still seeing uncaught promises with the same `LF will be replaced ... etc` error.

**Comment by akonwi** [comment]
That's baffling. I've pushed another change which should catch those rejected promises and log about it again

**Comment by RangerMauve** [comment]
Was it to that branch you made, or to the new release?

**Comment by akonwi** [comment]
The 310 branch

**Comment by icimasa** [comment]
Hi,

I have the same issue, I have to open "Add all and commit" twice before the edit commit message appears, and ctrl-S twice to save it, and also before in the edit commit message pane you would be able to see all files that will be committed, however now it is just a blank page??

**Comment by alessandrotesoro** [comment]
Having the same issue here, cannot commit anymore.

**Comment by atom-project** [comment]
This bug exists since 2 weeks on windows. This is really annoying.

**Comment by RangerMauve** [comment]
Have any of you guys had time to try the 310 branch that was made to fix this? I've been super busy and haven't gotten around to the latest push there.

**Comment by atom-project** [comment]
the 310 branch works for me :+1:  thx

**Comment by RangerMauve** [comment]
Awesome! I guess that means this will be fixed for everyone as soon as @akonwi releases it. :D

**Comment by atom-project** [comment]
newst version works now...
