### ISSUE TITLE
Context menu commands doesn't work anymore

### ISSUE THREAD

**Issue by qkzk** [akonwi/git-plus#587]
[The context menu commands doesn't work anymore - the packages menu commands still work]

Steps to reproduce:

1. Edit a file
2. **Right click it in project folder, Git, add + commit. -> Doesn't do anything**
3. Click Packages menu, Git plus, add + commit -> works

Not a single command work from the right click menu, all of them works from packages menu.

It worked perfectly 4 days ago.

system : windows 10 - 64 bits, 
atom : 1.12.8
git plus : 7.0.4 - standard settings
git desktop : correctly installed in program files and working
packages : atom-clock, file icons, minimap, script (every thing is up to date)

Thanks a lot for this game breaker addon :)

**Comment by akonwi** [comment]
Can you send a video or gif of this?

**Comment by qkzk** [comment]
Ill do it as soon as I get up.



Le 4 janv. 2017 11:21 PM, "Akonwi Ngoh" <notifications@github.com> a écrit :

Can you send a video or gif of this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/akonwi/git-plus/issues/587#issuecomment-270504118>, or mute
the thread

**Comment by qkzk** [comment]
https://youtu.be/L-Vpg5SuWHg
Here is a video of the bug. I realise I could have clicked on the pin icon to show you the git console. 
Well, it says `nothing to show` as long as i right click on the folder and it shows the correct logs when I use the Packages menu.

**Comment by akonwi** [comment]
This is really weird. Can you open the dev console with the `Window: Toggle Dev Tools` command and then use the context menu again? There might be some output in the console that may be helpful in understanding what's going on.

**Comment by qkzk** [comment]
In the console I could find :

warnings from launching
1. ::shadow pseudo-element is deprecated. See
https://www.chromestatus.com/features/6750456638341120 for more details.
2. /deep/ combinator is deprecated. See
https://www.chromestatus.com/features/6750456638341120 for more details.

errors when clicking commit + add from context
3. Uncaught (in promise) TypeError: Cannot read property 'repo' of null(…)
(anonymous function) @ git.coffee:140
4. Uncaught (in promise) TypeError: Cannot read property 'repo' of null(…)
(anonymous function) @ git.coffee:140

The package commands are working correctly.

**Comment by qkzk** [comment]
I forgot to say that I clicked twice.

The link leads to :

getRepoForPath: (path) ->
    if not path?
      Promise.reject "No file to find repository for"
    else
      new Promise (resolve, reject) ->
        project = atom.project
        directory = project.getDirectories().filter((d) -> d.contains(path)
or d.getPath() is path)[0]
        if directory?
          project.repositoryForDirectory(directory)
          .then (repo) ->
            submodule = repo.repo.submoduleForPath(path)
            if submodule? then resolve(submodule) else resolve(repo)
          .catch (e) ->
            reject(e)
        else
          reject "no current file"

with the 140th line starting with "submodule..."

**Comment by akonwi** [comment]
This is peculiar. I pushed a new update which should more gracefully handle the error by displaying a notification and then logging to the console.

I don't really understand why it's happening though because it seems like it can't find a repository

**Comment by qkzk** [comment]
I just tested the 7.0.5 version. The notification is there but the error
too...

In a few days I'll be setting up a new deskop with another OS. Since I'll
keep exactly the same packages for atom, I'll keep you informed if it
changes anything.

**Comment by akonwi** [comment]
I added the notification so there would be visible feedback. 

Unfortunately I can't replicate this. That would make it a lot easier to figure out what's going on

**Comment by qkzk** [comment]
Hello, I switched from win10 to debian jessie desktop. Same packages but no theme. The error is still there.
Packages : beautify, clock, file-icons & minimap. The error persist even if i disable all of them.

**Comment by akonwi** [comment]
I just pushed a new update with changes around looking for the repository to work with. Give 7.0.7 a shot

**Comment by qkzk** [comment]
Unfortunatelly we're back to step one.
The error is still there
(*/home/xxxxxxxx/.atom/packages/git-plus/lib/git.coffee:274
Uncaught (in promise) TypeError: Cannot read property 'getWorkingDirectory'
of null(…)*)

The notification doesn't show up anymore :(

The package menu still works fine.

**Comment by akonwi** [comment]
Haha wow.

I pushed a new branch called [587](https://github.com/akonwi/git-plus/tree/587). Can you clone that and replace your `~/.atom/packages/git-plus` with it? 

The version on that branch has some extra logging that should help determine what the package thinks the path is for the file your clicking on in the tree-view and if atom is responding correctly regarding the repositories in the project.

**Comment by qkzk** [comment]
Failed to load gitplus package.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.9
**Electron Version**: 1.3.13
**System**: Debian GNU/Linux
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package,
v7.0.7


### Stack Trace

Failed to activate the git-plus package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename
(/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename
(/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require
(/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous>
(/home/quentin/.atom/packages/git-plus/lib/git-plus.coffee:2:26)
    at Object.<anonymous>
(/home/quentin/.atom/packages/git-plus/lib/git-plus.coffee:1:1)
    at Module._compile
(/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .coffee]
(/usr/share/atom/resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require
(/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule
(/usr/share/atom/resources/app.asar/src/package.js:747:27)
    at Package.module.exports.Package.activateNow
(/usr/share/atom/resources/app.asar/src/package.js:174:16)
    at /usr/share/atom/resources/app.asar/src/package.js:157:32
    at Package.module.exports.Package.measure
(/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:150:26
    at Package.module.exports.Package.activate
(/usr/share/atom/resources/app.asar/src/package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage
(/usr/share/atom/resources/app.asar/src/package-manager.js:550:34)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync
(/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages
(/usr/share/atom/resources/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate
(/usr/share/atom/resources/app.asar/src/package-manager.js:508:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:792:28
```

### Commands

```
     -0:00.0 tree-view:show
(atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "no"
  },
  "git-plus": {
    "general": {
      "_analyticsUserId": "e3385980-bb8b-46a2-980f-04978dc8bab8"
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.16 (inactive)
atom-clock, v0.1.2 (inactive)
file-icons, v2.0.8 (inactive)
git-plus, v7.0.7 (inactive)
minimap, v4.26.5 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.13.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.4 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.2 (inactive)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.4 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.2 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.0 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by akonwi** [comment]
Sorry I forgot to mention you'll need to run 'apm install` from inside the directory

**Comment by qkzk** [comment]
There's another error, can't find atom-space-pen-views

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.9
**Electron Version**: 1.3.13
**System**: Debian GNU/Linux
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package,
v7.0.7


### Stack Trace

Failed to activate the git-plus package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename
(/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename
(/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require
(/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous>
(/home/quentin/.atom/packages/git-plus/lib/git-plus.coffee:2:26)
    at Object.<anonymous>
(/home/quentin/.atom/packages/git-plus/lib/git-plus.coffee:1:1)
    at Module._compile
(/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .coffee]
(/usr/share/atom/resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require
(/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule
(/usr/share/atom/resources/app.asar/src/package.js:747:27)
    at Package.module.exports.Package.activateNow
(/usr/share/atom/resources/app.asar/src/package.js:174:16)
    at /usr/share/atom/resources/app.asar/src/package.js:157:32
    at Package.module.exports.Package.measure
(/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:150:26
    at Package.module.exports.Package.activate
(/usr/share/atom/resources/app.asar/src/package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage
(/usr/share/atom/resources/app.asar/src/package-manager.js:550:34)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync
(/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages
(/usr/share/atom/resources/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate
(/usr/share/atom/resources/app.asar/src/package-manager.js:508:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:792:28
```

### Commands

```
     -0:00.0 tree-view:show
(atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "no"
  },
  "git-plus": {
    "general": {
      "_analyticsUserId": "e3385980-bb8b-46a2-980f-04978dc8bab8"
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.16 (inactive)
atom-clock, v0.1.2 (inactive)
file-icons, v2.0.8 (inactive)
git-plus, v7.0.7 (inactive)
minimap, v4.26.5 (inactive)
node_modules, vundefined (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.13.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.4 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.2 (inactive)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.4 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.2 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.0 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by akonwi** [comment]
did you run `apm install` from within the directory you cloned?

**Comment by qkzk** [comment]
Here's what I did :
deleted *~/.atom/package/git-plus. *Should I uninstall it first ?
mv the new branch at the same place. *apm install* from git-plus directory.
Launched atom. It gave me the error I parsed you.

I'll try to remove git-plus first from atom and then install the new branch
with apm when I'll get back home tonight.

**Comment by mcarpenterjr** [comment]
Hey, I see you are working on the same issue I'm currently encountering, except my context menu worked until you pushed 7.0.7. I'm running on Linux Mint 18. I'm new to working with package issues but would like to lend a hand. 

I follow instructions. :smiley: pretty good.

**Comment by akonwi** [comment]
@mcarpenterjr If you can clone this [branch](https://github.com/akonwi/git-plus/tree/587), replace your local `~/.atom/packages/git-plus` with it, and run `cd ~/.atom/packages/git-plus && apm install` that would be good.

That branch will log some more info when you run a context command from the tree-view. Can you share what you see there?

**Comment by eLn86** [comment]
How do I run apm install on windows? I tried doing it via the command prompt and navigating to the directory and "&& install" but it didn't work. I tried re-installing git-plus and also restarting my computer. The context menu was working perfectly fine, but suddenly I could not open it either by the atom packages tab or by ctrl+shift+H. Nothing works at all now.. please help..

**Comment by akonwi** [comment]
Running `apm install` from the command line doesn't work? If so, check and make sure `atom` and `apm` are in your PATH

**Comment by eLn86** [comment]
Yea, that's because I run windows. Fortunately, because it's windows 10, i was able to get Bash on Ubuntu. And then the apm install worked, thanks!
